// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lotlmcgiqivrljhqljui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdGxtY2dpcWl2cmxqaHFsanVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDUwNTAsImV4cCI6MjA2MzIyMTA1MH0.nxyGEROLI-3UBCgwijHCm9YtORtzmmEJJjRn0YoURSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);